import { Queue } from "bullmq";
import { db, departments, departmentTasks, agentRuns } from "@mammoth/memory-database";
import { eq, and } from "drizzle-orm";
import type { AgentJobData } from "@mammoth/agent-base";
import { QUEUE_NAMES } from "@mammoth/agent-base";

import { createLogger } from "@mammoth/observability/logger";

const log = createLogger("department-dispatcher");

const REDIS_CONNECTION = {
  host: process.env["REDIS_HOST"] ?? "localhost",
  port: Number(process.env["REDIS_PORT"] ?? 6379),
  password: process.env["REDIS_PASSWORD"] ?? undefined,
  maxRetriesPerRequest: null,
} as const;

export type DepartmentPriority = {
  department: string;
  focus: string;
  weeklyTarget: string;
};

// Maps each department name to the task type that aligns with its priority focus
const DEPARTMENT_TASK_TYPE_MAP: Record<string, string> = {
  marketing: "social_post",
  sales: "lead_research",
  engineering: "sprint_planning",
  support: "create_kb_article",
  research: "competitor_intel",
  hr: "job_posting",
  content: "blog_post",
  finance: "financial_report",
};

/**
 * Dispatches department tasks based on CEO Brain priorities.
 * Creates a departmentTask row + queues a BullMQ job for each department priority.
 * This is the orchestration layer: CEO Brain → Department agents.
 * Called once per CEO Brain cycle (every 6h).
 *
 * @param companyId  - The company to dispatch tasks for
 * @param priorities - Priorities generated by the CEO Brain
 */
/**
 * Returns the agentRunId created for this dispatch batch.
 * Used by the LangGraph dispatch node to track what was queued.
 */
export async function dispatchDepartmentTasks(
  companyId: string,
  priorities: DepartmentPriority[]
): Promise<string> {
  if (priorities.length === 0) return "";

  const agentQueue = new Queue<AgentJobData>(QUEUE_NAMES.AGENT_TASKS, {
    connection: REDIS_CONNECTION,
  });

  // Create a single agent run for this CEO cycle to track all dispatched tasks
  const [agentRun] = await db
    .insert(agentRuns)
    .values({
      companyId,
      department: "ceo_brain",
      runType: "scheduled",
      triggerSource: "ceo_brain_cycle",
      status: "running",
      tasksCreated: priorities.length,
    })
    .returning({ id: agentRuns.id });

  if (!agentRun) {
    log.warn("Could not create agent run for department dispatch", { companyId });
    return "";
  }

  const agentRunId = agentRun.id;
  let dispatched = 0;

  for (const priority of priorities) {
    const deptName = priority.department.toLowerCase();
    const taskType = DEPARTMENT_TASK_TYPE_MAP[deptName];

    if (!taskType) {
      log.warn("No task type mapping for department", { companyId, department: deptName });
      continue;
    }

    const dept = await db.query.departments.findFirst({
      where: and(
        eq(departments.companyId, companyId),
        // departments.name is a typed enum — cast to satisfy the type checker
        eq(departments.name, deptName as "marketing" | "sales" | "engineering" | "support" | "finance" | "research" | "hr" | "content" | "ceo")
      ),
      columns: { id: true, status: true },
    });

    if (!dept || dept.status !== "active") continue;

    // Create the task row first — the agent-worker resolves department from this row
    const [createdTask] = await db
      .insert(departmentTasks)
      .values({
        companyId,
        departmentId: dept.id,
        title: `${deptName}: ${priority.focus.slice(0, 120)}`,
        taskType,
        status: "queued",
        inputData: {
          focus: priority.focus,
          weeklyTarget: priority.weeklyTarget,
          ceoRunId: agentRunId,
          // Pass sensible defaults per task type
          ...(taskType === "lead_research" ? { icp: priority.focus, count: 10 } : {}),
          ...(taskType === "social_post" ? { topic: priority.focus } : {}),
          ...(taskType === "blog_post" ? { topic: priority.focus } : {}),
          ...(taskType === "competitor_intel" ? {} : {}),
          ...(taskType === "sprint_planning" ? { goals: [priority.weeklyTarget], teamCapacity: 40 } : {}),
        },
      })
      .returning({ id: departmentTasks.id });

    if (!createdTask) continue;

    const jobData: AgentJobData = {
      companyId,
      departmentId: dept.id,
      taskId: createdTask.id,
      agentRunId,
      taskType,
      parameters: {
        focus: priority.focus,
        weeklyTarget: priority.weeklyTarget,
        ...(taskType === "lead_research" ? { icp: priority.focus, count: 10 } : {}),
        ...(taskType === "social_post" ? { topic: priority.focus } : {}),
        ...(taskType === "blog_post" ? { topic: priority.focus } : {}),
        ...(taskType === "sprint_planning" ? { goals: [priority.weeklyTarget], teamCapacity: 40 } : {}),
        ...(taskType === "create_kb_article" ? { topic: priority.focus } : {}),
        ...(taskType === "competitor_intel" ? {} : {}),
      },
    };

    await agentQueue.add(
      `${taskType}:${companyId}:ceo-dispatch`,
      jobData,
      {
        jobId: `ceo-dispatch:${companyId}:${deptName}:${Date.now()}`,
        removeOnComplete: { count: 200 },
        removeOnFail: { count: 100 },
        // Stagger department tasks 30s apart to prevent thundering herd
        delay: dispatched * 30_000,
      }
    );

    dispatched++;
    log.info("Department task queued", { companyId, department: deptName, taskType, taskId: createdTask.id });
  }

  log.info("CEO Brain dispatch complete", { companyId, total: priorities.length, dispatched, agentRunId });

  await agentQueue.close();
  return agentRunId;
}
